name: Build and Release of ParchLinux WSL Image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Updating system packages..."
          pacman -Syu --noconfirm || { echo 'pacman update failed!'; exit 1; }
          echo "Installing necessary packages..."
          pacman -S --noconfirm \
            make \
            devtools \
            fakechroot \
            fakeroot \
            git \
            python \
            curl \
            base-devel || { echo 'pacman install failed!'; exit 1; }

      - name: Build ParchLinux WSL image
        run: |
          echo "Building the ParchLinux WSL image..."
          make build || { echo 'Make build failed!'; exit 1; }

      - name: Find .wsl artifact
        id: find-artifact
        run: |
          ARTIFACT=$(find workdir/output -type f -name "*.wsl" | sort | tail -n 1)
          if [ -z "$ARTIFACT" ]; then
            echo "No .wsl artifact found!"
            exit 1
          fi
          echo "Found artifact: $ARTIFACT"
          echo "artifact_path=$ARTIFACT" >> "$GITHUB_OUTPUT"

      - name: Upload artifact to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find-artifact.outputs.artifact_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
